# Sample configuration file for Sidekiq.
# Options here can still be overridden by cmd line args.
# Place this file at config/sidekiq.yml and Sidekiq will
# pick it up automatically.
---
:verbose: false
:concurrency: 10
:timeout: 250
:pidfile: tmp/pid/sidekiq.pid

# Sidekiq will run this file through ERB when reading it so you can
# even put in dynamic logic, like a host-specific queue.
# http://www.mikeperham.com/2013/11/13/advanced-sidekiq-host-specific-queues/
:queues:
  - critical
  - default
  - low

# you can override concurrency based on environment
production:
  :concurrency: 25
staging:
  :concurrency: 15

:schedule:
  printer_labels_call:
    cron: '*/1 * * * *' # Runs every 1 minute
    class: PrinterJob
  set_printer_call:
  cron: '*/1 * * * *' # Runs every 1 minute
  class: 

